package menuPrincipal;

import conexionDB.conexionMysql;
import forms.RespuestaSeleccionUsuario;
import forms.tbDatoCurioso;
import forms.tb_historico;
import forms.tb_quiz;
import forms.tb_respuestas;
import java.util.ArrayList;
import java.util.List;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.time.LocalDate;
import java.util.Collections;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import forms.Cronometro;
import forms.render;
import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;
import javax.swing.JButton;

/**
 *
 * @author Maluli
 */
public class Principal extends javax.swing.JFrame {

    conexionMysql conexionDB = null;
    int recorridoPlay = 0;
    List<tb_quiz> listaPreguntasPlay = new ArrayList<>();
    List<RespuestaSeleccionUsuario> listaRespuestaPlay = new ArrayList<>();
    int totalPreguntasCorrectas = 0;
    String nombreAlumno = "";
    String apellidoAlumno = "";
    int idLogin;
    int k = 0;

    Cronometro cronometro = new Cronometro(1000, new ActionListener() {
        @Override
        public void actionPerformed(ActionEvent e) {
            // Actualiza el JLabel con el tiempo transcurrido
            k++;
            etiquetaTiempo.setText(String.valueOf(k) + " segundos");

        }
    });

    /**
     * Creates new form Principal
     */
    public Principal() {
        //inicio de componentes
        initComponents();

        conexionDB = new conexionMysql();
        this.consultaTablaHistorico();
        this.panelInicio.setVisible(true);
        this.panelHistorico.setVisible(false);
        this.panelConfig.setVisible(false);
        this.panelPlay.setVisible(false);
        this.panelQuiz.setVisible(false);
        this.panelCalificacion.setVisible(false);
        this.panelEducacion.setVisible(false);
        this.panelDatoCurioso.setVisible(false);
        this.panelEditConfig.setVisible(false);
        this.getPizarra1();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGrupoConfigPreguntas = new javax.swing.ButtonGroup();
        btnGrupoPreguntas = new javax.swing.ButtonGroup();
        panelContenedor = new javax.swing.JPanel();
        jugar = new javax.swing.JButton();
        Configuracion = new javax.swing.JButton();
        inicio = new javax.swing.JButton();
        historico = new javax.swing.JButton();
        datoCurioso = new javax.swing.JButton();
        preguntas = new javax.swing.JButton();
        panelDatoCurioso = new javax.swing.JPanel();
        actualizarTema1 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        actualizarTema2 = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        temaEstudio1 = new javax.swing.JTextArea();
        jScrollPane5 = new javax.swing.JScrollPane();
        temaEstudio2 = new javax.swing.JTextArea();
        panelConfig = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        guardarPreguntaRespConf = new javax.swing.JButton();
        cancelarPreguntaRespConf = new javax.swing.JButton();
        resp1 = new javax.swing.JTextField();
        preguntaConf = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        resp3 = new javax.swing.JTextField();
        resp2 = new javax.swing.JTextField();
        resp4 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        validateBtn4 = new javax.swing.JRadioButton();
        validateBtn3 = new javax.swing.JRadioButton();
        validateBtn2 = new javax.swing.JRadioButton();
        validateBtn1 = new javax.swing.JRadioButton();
        panelEditConfig = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jScrollPane8 = new javax.swing.JScrollPane();
        tablaPreguntas = new javax.swing.JTable();
        panelInicio = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        pizarra1 = new javax.swing.JTextArea();
        panelEducacion = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        pizarra2 = new javax.swing.JTextArea();
        panelHistorico = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaHistorico = new javax.swing.JTable();
        panelPlay = new javax.swing.JPanel();
        btnSencillo = new javax.swing.JButton();
        btnDificil = new javax.swing.JButton();
        btnNormal = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        panelQuiz = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        labelNumPregunta = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        rbPlayOpt1 = new javax.swing.JRadioButton();
        rbPlayOpt2 = new javax.swing.JRadioButton();
        rbPlayOpt3 = new javax.swing.JRadioButton();
        rbPlayOpt4 = new javax.swing.JRadioButton();
        btnPlayNextQuestion = new javax.swing.JButton();
        btnFinalizarPlay = new javax.swing.JButton();
        jScrollPane6 = new javax.swing.JScrollPane();
        playPregunta = new javax.swing.JTextArea();
        jScrollPane7 = new javax.swing.JScrollPane();
        playRespuesta2 = new javax.swing.JTextArea();
        jScrollPane9 = new javax.swing.JScrollPane();
        playRespuesta3 = new javax.swing.JTextArea();
        jScrollPane10 = new javax.swing.JScrollPane();
        playRespuesta4 = new javax.swing.JTextArea();
        jScrollPane11 = new javax.swing.JScrollPane();
        playRespuesta1 = new javax.swing.JTextArea();
        etiquetaTiempo = new javax.swing.JLabel();
        panelCalificacion = new javax.swing.JPanel();
        btnSalirdeQuiz = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        calificacion = new javax.swing.JLabel();
        TiempoTotal = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        panelContenedor.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jugar.setBackground(new java.awt.Color(0, 102, 73));
        jugar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jugar.setForeground(new java.awt.Color(255, 255, 255));
        jugar.setText("Jugar");
        jugar.setBorder(null);
        jugar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jugar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jugarActionPerformed(evt);
            }
        });
        panelContenedor.add(jugar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 160, 40));

        Configuracion.setBackground(new java.awt.Color(0, 102, 73));
        Configuracion.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Configuracion.setForeground(new java.awt.Color(255, 255, 255));
        Configuracion.setText("Configuración");
        Configuracion.setBorder(null);
        Configuracion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Configuracion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConfiguracionActionPerformed(evt);
            }
        });
        panelContenedor.add(Configuracion, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, 160, 40));

        inicio.setBackground(new java.awt.Color(0, 102, 73));
        inicio.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        inicio.setForeground(new java.awt.Color(255, 255, 255));
        inicio.setText("Inicio");
        inicio.setBorder(null);
        inicio.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        inicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inicioActionPerformed(evt);
            }
        });
        panelContenedor.add(inicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 160, 40));

        historico.setBackground(new java.awt.Color(0, 102, 73));
        historico.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        historico.setForeground(new java.awt.Color(255, 255, 255));
        historico.setText("Histórico");
        historico.setBorder(null);
        historico.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        historico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                historicoActionPerformed(evt);
            }
        });
        panelContenedor.add(historico, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 160, 40));

        datoCurioso.setBackground(new java.awt.Color(0, 102, 73));
        datoCurioso.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        datoCurioso.setForeground(new java.awt.Color(255, 255, 255));
        datoCurioso.setText("Tema de estudio");
        datoCurioso.setBorder(null);
        datoCurioso.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        datoCurioso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                datoCuriosoActionPerformed(evt);
            }
        });
        panelContenedor.add(datoCurioso, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 160, 40));

        preguntas.setBackground(new java.awt.Color(0, 102, 73));
        preguntas.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        preguntas.setForeground(new java.awt.Color(255, 255, 255));
        preguntas.setText("Preguntas");
        preguntas.setBorder(null);
        preguntas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        preguntas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                preguntasActionPerformed(evt);
            }
        });
        panelContenedor.add(preguntas, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, 160, 40));

        panelDatoCurioso.setBackground(new java.awt.Color(255, 255, 255));
        panelDatoCurioso.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(161, 211, 161), 5, true));
        panelDatoCurioso.setForeground(new java.awt.Color(243, 244, 243));

        actualizarTema1.setBackground(new java.awt.Color(0, 102, 51));
        actualizarTema1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        actualizarTema1.setForeground(new java.awt.Color(255, 255, 255));
        actualizarTema1.setText("Actualizar primer tema");
        actualizarTema1.setBorder(null);
        actualizarTema1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actualizarTema1ActionPerformed(evt);
            }
        });

        jLabel13.setBackground(new java.awt.Color(102, 0, 204));
        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 102, 102));
        jLabel13.setText("Temas de estudio para los estudiantes");

        actualizarTema2.setBackground(new java.awt.Color(0, 102, 51));
        actualizarTema2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        actualizarTema2.setForeground(new java.awt.Color(255, 255, 255));
        actualizarTema2.setText("Actualizar segundo tema");
        actualizarTema2.setBorder(null);
        actualizarTema2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actualizarTema2ActionPerformed(evt);
            }
        });

        temaEstudio1.setColumns(20);
        temaEstudio1.setLineWrap(true);
        temaEstudio1.setRows(12);
        temaEstudio1.setWrapStyleWord(true);
        temaEstudio1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 51), 2));
        jScrollPane4.setViewportView(temaEstudio1);

        temaEstudio2.setColumns(20);
        temaEstudio2.setLineWrap(true);
        temaEstudio2.setRows(12);
        temaEstudio2.setWrapStyleWord(true);
        temaEstudio2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 51), 2));
        jScrollPane5.setViewportView(temaEstudio2);

        javax.swing.GroupLayout panelDatoCuriosoLayout = new javax.swing.GroupLayout(panelDatoCurioso);
        panelDatoCurioso.setLayout(panelDatoCuriosoLayout);
        panelDatoCuriosoLayout.setHorizontalGroup(
            panelDatoCuriosoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDatoCuriosoLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(panelDatoCuriosoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panelDatoCuriosoLayout.createSequentialGroup()
                        .addGroup(panelDatoCuriosoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(actualizarTema1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 281, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelDatoCuriosoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 282, Short.MAX_VALUE)
                            .addComponent(actualizarTema2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(28, 28, 28))
        );
        panelDatoCuriosoLayout.setVerticalGroup(
            panelDatoCuriosoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelDatoCuriosoLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelDatoCuriosoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 253, Short.MAX_VALUE)
                    .addComponent(jScrollPane5))
                .addGap(18, 18, 18)
                .addGroup(panelDatoCuriosoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(actualizarTema1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(actualizarTema2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelContenedor.add(panelDatoCurioso, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 80, 630, 400));

        panelConfig.setBackground(new java.awt.Color(255, 255, 255));
        panelConfig.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(161, 211, 161), 5, true));
        panelConfig.setForeground(new java.awt.Color(243, 244, 243));

        jLabel1.setBackground(new java.awt.Color(205, 221, 213));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 102));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/edit-tools.png"))); // NOI18N
        jLabel1.setText("Configuración de preguntas y respuestas");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 102, 51));
        jLabel2.setText("Pregunta");

        guardarPreguntaRespConf.setBackground(new java.awt.Color(0, 102, 51));
        guardarPreguntaRespConf.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        guardarPreguntaRespConf.setForeground(new java.awt.Color(255, 255, 255));
        guardarPreguntaRespConf.setText("Guardar");
        guardarPreguntaRespConf.setBorder(null);
        guardarPreguntaRespConf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarPreguntaRespConfActionPerformed(evt);
            }
        });

        cancelarPreguntaRespConf.setBackground(new java.awt.Color(209, 220, 215));
        cancelarPreguntaRespConf.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cancelarPreguntaRespConf.setForeground(new java.awt.Color(0, 102, 51));
        cancelarPreguntaRespConf.setText("Cancelar");
        cancelarPreguntaRespConf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarPreguntaRespConfActionPerformed(evt);
            }
        });

        resp1.setColumns(3);

        jLabel4.setText("Seleccione la respuesta que usted evaluará como correcta");

        resp3.setColumns(3);
        resp3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resp3ActionPerformed(evt);
            }
        });

        resp2.setColumns(3);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 102, 51));
        jLabel5.setText("Respuestas");

        btnGrupoConfigPreguntas.add(validateBtn4);

        btnGrupoConfigPreguntas.add(validateBtn3);

        btnGrupoConfigPreguntas.add(validateBtn2);

        btnGrupoConfigPreguntas.add(validateBtn1);

        javax.swing.GroupLayout panelConfigLayout = new javax.swing.GroupLayout(panelConfig);
        panelConfig.setLayout(panelConfigLayout);
        panelConfigLayout.setHorizontalGroup(
            panelConfigLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 620, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelConfigLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelConfigLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(preguntaConf, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelConfigLayout.createSequentialGroup()
                        .addComponent(validateBtn4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelConfigLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelConfigLayout.createSequentialGroup()
                                .addGap(0, 339, Short.MAX_VALUE)
                                .addComponent(cancelarPreguntaRespConf, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(guardarPreguntaRespConf, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(resp4)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelConfigLayout.createSequentialGroup()
                        .addGroup(panelConfigLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelConfigLayout.createSequentialGroup()
                        .addGroup(panelConfigLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(validateBtn1)
                            .addComponent(validateBtn2)
                            .addComponent(validateBtn3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelConfigLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(resp3)
                            .addComponent(resp1)
                            .addComponent(resp2))))
                .addContainerGap())
        );
        panelConfigLayout.setVerticalGroup(
            panelConfigLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelConfigLayout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(preguntaConf, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelConfigLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(resp1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(validateBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelConfigLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(resp2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(validateBtn2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(panelConfigLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(resp3, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(validateBtn3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(10, 10, 10)
                .addGroup(panelConfigLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(validateBtn4, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelConfigLayout.createSequentialGroup()
                        .addComponent(resp4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelConfigLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cancelarPreguntaRespConf, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(guardarPreguntaRespConf, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(15, 15, 15))
        );

        panelContenedor.add(panelConfig, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 80, 630, 400));

        panelEditConfig.setBackground(new java.awt.Color(255, 255, 255));
        panelEditConfig.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(161, 211, 161), 5, true));
        panelEditConfig.setForeground(new java.awt.Color(243, 244, 243));

        jLabel14.setBackground(new java.awt.Color(102, 0, 204));
        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 102, 102));
        jLabel14.setText("Preguntas registradas");

        tablaPreguntas.setBackground(new java.awt.Color(0, 102, 51));
        tablaPreguntas.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tablaPreguntas.setForeground(new java.awt.Color(255, 255, 255));
        tablaPreguntas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tablaPreguntas.setToolTipText("");
        tablaPreguntas.setEnabled(false);
        tablaPreguntas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaPreguntasMouseClicked(evt);
            }
        });
        jScrollPane8.setViewportView(tablaPreguntas);

        javax.swing.GroupLayout panelEditConfigLayout = new javax.swing.GroupLayout(panelEditConfig);
        panelEditConfig.setLayout(panelEditConfigLayout);
        panelEditConfigLayout.setHorizontalGroup(
            panelEditConfigLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panelEditConfigLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 533, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelEditConfigLayout.setVerticalGroup(
            panelEditConfigLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEditConfigLayout.createSequentialGroup()
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelContenedor.add(panelEditConfig, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 80, 620, 400));

        panelInicio.setBackground(new java.awt.Color(255, 255, 255));
        panelInicio.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(161, 211, 161), 5, true));
        panelInicio.setForeground(new java.awt.Color(243, 244, 243));

        jLabel3.setBackground(new java.awt.Color(102, 0, 204));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 102, 102));
        jLabel3.setText("Ecomindful te enseña...");

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/profe.png"))); // NOI18N

        jButton1.setBackground(new java.awt.Color(0, 102, 51));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Leer más");
        jButton1.setBorder(null);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        pizarra1.setEditable(false);
        pizarra1.setBackground(new java.awt.Color(210, 236, 231));
        pizarra1.setColumns(20);
        pizarra1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        pizarra1.setForeground(new java.awt.Color(0, 102, 51));
        pizarra1.setLineWrap(true);
        pizarra1.setRows(12);
        pizarra1.setWrapStyleWord(true);
        pizarra1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 51), 4));
        pizarra1.setSelectionColor(new java.awt.Color(0, 102, 51));
        jScrollPane2.setViewportView(pizarra1);

        javax.swing.GroupLayout panelInicioLayout = new javax.swing.GroupLayout(panelInicio);
        panelInicio.setLayout(panelInicioLayout);
        panelInicioLayout.setHorizontalGroup(
            panelInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInicioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelInicioLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(panelInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 335, Short.MAX_VALUE)
                            .addComponent(jScrollPane2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel8)
                        .addGap(29, 29, 29))
                    .addGroup(panelInicioLayout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        panelInicioLayout.setVerticalGroup(
            panelInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInicioLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(panelInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelInicioLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelInicioLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, 0))
        );

        panelContenedor.add(panelInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 80, 620, 400));

        panelEducacion.setBackground(new java.awt.Color(255, 255, 255));
        panelEducacion.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(161, 211, 161), 5, true));
        panelEducacion.setForeground(new java.awt.Color(243, 244, 243));

        jButton2.setBackground(new java.awt.Color(0, 102, 51));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Regresar");
        jButton2.setBorder(null);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/profesora.png"))); // NOI18N

        pizarra2.setEditable(false);
        pizarra2.setBackground(new java.awt.Color(210, 236, 231));
        pizarra2.setColumns(20);
        pizarra2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        pizarra2.setForeground(new java.awt.Color(0, 102, 51));
        pizarra2.setLineWrap(true);
        pizarra2.setRows(12);
        pizarra2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 51), 4));
        pizarra2.setSelectionColor(new java.awt.Color(0, 102, 51));
        jScrollPane3.setViewportView(pizarra2);

        javax.swing.GroupLayout panelEducacionLayout = new javax.swing.GroupLayout(panelEducacion);
        panelEducacion.setLayout(panelEducacionLayout);
        panelEducacionLayout.setHorizontalGroup(
            panelEducacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelEducacionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelEducacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 339, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelEducacionLayout.setVerticalGroup(
            panelEducacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelEducacionLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(panelEducacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panelEducacionLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 398, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        panelContenedor.add(panelEducacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 80, 620, 400));

        panelHistorico.setBackground(new java.awt.Color(255, 255, 255));
        panelHistorico.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(161, 211, 161), 5, true));
        panelHistorico.setForeground(new java.awt.Color(243, 244, 243));

        jLabel6.setBackground(new java.awt.Color(102, 0, 204));
        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 102, 102));
        jLabel6.setText("Histórico de puntajes");

        tablaHistorico.setBackground(new java.awt.Color(0, 102, 51));
        tablaHistorico.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tablaHistorico.setForeground(new java.awt.Color(255, 255, 255));
        tablaHistorico.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tablaHistorico.setToolTipText("");
        tablaHistorico.setEnabled(false);
        jScrollPane1.setViewportView(tablaHistorico);

        javax.swing.GroupLayout panelHistoricoLayout = new javax.swing.GroupLayout(panelHistorico);
        panelHistorico.setLayout(panelHistoricoLayout);
        panelHistoricoLayout.setHorizontalGroup(
            panelHistoricoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panelHistoricoLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 533, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelHistoricoLayout.setVerticalGroup(
            panelHistoricoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelHistoricoLayout.createSequentialGroup()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelContenedor.add(panelHistorico, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 80, 620, 400));

        panelPlay.setBackground(new java.awt.Color(255, 255, 255));
        panelPlay.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(161, 211, 161), 5, true));
        panelPlay.setForeground(new java.awt.Color(243, 244, 243));

        btnSencillo.setBackground(new java.awt.Color(0, 102, 51));
        btnSencillo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnSencillo.setForeground(new java.awt.Color(255, 255, 255));
        btnSencillo.setText("Sencillo");
        btnSencillo.setBorder(null);
        btnSencillo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSencilloActionPerformed(evt);
            }
        });

        btnDificil.setBackground(new java.awt.Color(0, 102, 51));
        btnDificil.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnDificil.setForeground(new java.awt.Color(255, 255, 255));
        btnDificil.setText("Difícil");
        btnDificil.setBorder(null);
        btnDificil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDificilActionPerformed(evt);
            }
        });

        btnNormal.setBackground(new java.awt.Color(0, 102, 51));
        btnNormal.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnNormal.setForeground(new java.awt.Color(255, 255, 255));
        btnNormal.setText("Normal");
        btnNormal.setBorder(null);
        btnNormal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNormalActionPerformed(evt);
            }
        });

        jLabel7.setBackground(new java.awt.Color(102, 0, 204));
        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 102, 102));
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/capas.png"))); // NOI18N
        jLabel7.setText("Seleccione un nivel para continuar");

        javax.swing.GroupLayout panelPlayLayout = new javax.swing.GroupLayout(panelPlay);
        panelPlay.setLayout(panelPlayLayout);
        panelPlayLayout.setHorizontalGroup(
            panelPlayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPlayLayout.createSequentialGroup()
                .addGroup(panelPlayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelPlayLayout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 608, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelPlayLayout.createSequentialGroup()
                        .addGap(111, 111, 111)
                        .addComponent(btnSencillo, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelPlayLayout.createSequentialGroup()
                        .addGap(111, 111, 111)
                        .addComponent(btnNormal, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelPlayLayout.createSequentialGroup()
                        .addGap(111, 111, 111)
                        .addComponent(btnDificil, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelPlayLayout.setVerticalGroup(
            panelPlayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPlayLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(btnSencillo, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnNormal, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnDificil, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        panelContenedor.add(panelPlay, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 80, 620, 400));

        panelQuiz.setBackground(new java.awt.Color(255, 255, 255));
        panelQuiz.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(161, 211, 161), 5, true));
        panelQuiz.setForeground(new java.awt.Color(243, 244, 243));

        jLabel9.setBackground(new java.awt.Color(102, 0, 204));
        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 102, 102));
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/boton-de-play.png"))); // NOI18N
        jLabel9.setText("Responda las siguientes preguntas:");

        labelNumPregunta.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        labelNumPregunta.setForeground(new java.awt.Color(0, 102, 51));
        labelNumPregunta.setText("Pregunta #1");

        jLabel11.setText("Seleccione la respuesta:");

        rbPlayOpt1.setBackground(new java.awt.Color(255, 255, 255));
        btnGrupoPreguntas.add(rbPlayOpt1);

        rbPlayOpt2.setBackground(new java.awt.Color(255, 255, 255));
        btnGrupoPreguntas.add(rbPlayOpt2);
        rbPlayOpt2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbPlayOpt2ActionPerformed(evt);
            }
        });

        rbPlayOpt3.setBackground(new java.awt.Color(255, 255, 255));
        btnGrupoPreguntas.add(rbPlayOpt3);
        rbPlayOpt3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbPlayOpt3ActionPerformed(evt);
            }
        });

        rbPlayOpt4.setBackground(new java.awt.Color(255, 255, 255));
        btnGrupoPreguntas.add(rbPlayOpt4);
        rbPlayOpt4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbPlayOpt4ActionPerformed(evt);
            }
        });

        btnPlayNextQuestion.setBackground(new java.awt.Color(0, 102, 51));
        btnPlayNextQuestion.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnPlayNextQuestion.setForeground(new java.awt.Color(255, 255, 255));
        btnPlayNextQuestion.setText("Siguiente");
        btnPlayNextQuestion.setBorder(null);
        btnPlayNextQuestion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlayNextQuestionActionPerformed(evt);
            }
        });

        btnFinalizarPlay.setBackground(new java.awt.Color(102, 102, 102));
        btnFinalizarPlay.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnFinalizarPlay.setForeground(new java.awt.Color(255, 255, 255));
        btnFinalizarPlay.setText("Finalizar");
        btnFinalizarPlay.setBorder(null);
        btnFinalizarPlay.setEnabled(false);
        btnFinalizarPlay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFinalizarPlayActionPerformed(evt);
            }
        });

        playPregunta.setEditable(false);
        playPregunta.setColumns(20);
        playPregunta.setLineWrap(true);
        playPregunta.setRows(2);
        playPregunta.setWrapStyleWord(true);
        jScrollPane6.setViewportView(playPregunta);

        playRespuesta2.setEditable(false);
        playRespuesta2.setColumns(20);
        playRespuesta2.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        playRespuesta2.setLineWrap(true);
        playRespuesta2.setRows(1);
        playRespuesta2.setTabSize(2);
        playRespuesta2.setWrapStyleWord(true);
        jScrollPane7.setViewportView(playRespuesta2);

        playRespuesta3.setEditable(false);
        playRespuesta3.setColumns(20);
        playRespuesta3.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        playRespuesta3.setLineWrap(true);
        playRespuesta3.setRows(1);
        playRespuesta3.setTabSize(2);
        playRespuesta3.setWrapStyleWord(true);
        jScrollPane9.setViewportView(playRespuesta3);

        playRespuesta4.setEditable(false);
        playRespuesta4.setColumns(20);
        playRespuesta4.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        playRespuesta4.setLineWrap(true);
        playRespuesta4.setRows(1);
        playRespuesta4.setTabSize(2);
        playRespuesta4.setWrapStyleWord(true);
        jScrollPane10.setViewportView(playRespuesta4);

        playRespuesta1.setEditable(false);
        playRespuesta1.setColumns(20);
        playRespuesta1.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        playRespuesta1.setLineWrap(true);
        playRespuesta1.setRows(1);
        playRespuesta1.setTabSize(2);
        playRespuesta1.setWrapStyleWord(true);
        jScrollPane11.setViewportView(playRespuesta1);

        javax.swing.GroupLayout panelQuizLayout = new javax.swing.GroupLayout(panelQuiz);
        panelQuiz.setLayout(panelQuizLayout);
        panelQuizLayout.setHorizontalGroup(
            panelQuizLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelQuizLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelQuizLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelQuizLayout.createSequentialGroup()
                        .addGroup(panelQuizLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelQuizLayout.createSequentialGroup()
                                .addComponent(rbPlayOpt4)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(panelQuizLayout.createSequentialGroup()
                                .addGroup(panelQuizLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rbPlayOpt2, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(rbPlayOpt3, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(rbPlayOpt1, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(panelQuizLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane7, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane10, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane9, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 583, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelQuizLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnPlayNextQuestion, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(btnFinalizarPlay, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelQuizLayout.createSequentialGroup()
                        .addGroup(panelQuizLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addGroup(panelQuizLayout.createSequentialGroup()
                                .addComponent(labelNumPregunta)
                                .addGap(18, 18, 18)
                                .addComponent(etiquetaTiempo)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panelQuizLayout.setVerticalGroup(
            panelQuizLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelQuizLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelQuizLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNumPregunta)
                    .addComponent(etiquetaTiempo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11)
                .addGap(0, 4, Short.MAX_VALUE)
                .addGroup(panelQuizLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rbPlayOpt1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelQuizLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(rbPlayOpt2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelQuizLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(rbPlayOpt3, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(panelQuizLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rbPlayOpt4, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelQuizLayout.createSequentialGroup()
                        .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelQuizLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnPlayNextQuestion, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnFinalizarPlay, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(20, 20, 20))
        );

        panelContenedor.add(panelQuiz, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 80, 630, 400));

        panelCalificacion.setBackground(new java.awt.Color(255, 255, 255));
        panelCalificacion.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 204, 0), 5, true));
        panelCalificacion.setForeground(new java.awt.Color(0, 102, 51));
        panelCalificacion.setToolTipText("");

        btnSalirdeQuiz.setBackground(new java.awt.Color(0, 102, 51));
        btnSalirdeQuiz.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnSalirdeQuiz.setForeground(new java.awt.Color(255, 255, 255));
        btnSalirdeQuiz.setText("Salir");
        btnSalirdeQuiz.setBorder(null);
        btnSalirdeQuiz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirdeQuizActionPerformed(evt);
            }
        });

        jLabel10.setBackground(new java.awt.Color(102, 0, 204));
        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 102, 102));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/gorro.png"))); // NOI18N

        jLabel12.setBackground(new java.awt.Color(102, 0, 204));
        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 102, 102));
        jLabel12.setText("Su calificación es:");

        calificacion.setBackground(new java.awt.Color(102, 0, 204));
        calificacion.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        calificacion.setForeground(new java.awt.Color(0, 102, 102));
        calificacion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        TiempoTotal.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        TiempoTotal.setForeground(new java.awt.Color(0, 102, 51));
        TiempoTotal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TiempoTotal.setToolTipText("");

        javax.swing.GroupLayout panelCalificacionLayout = new javax.swing.GroupLayout(panelCalificacion);
        panelCalificacion.setLayout(panelCalificacionLayout);
        panelCalificacionLayout.setHorizontalGroup(
            panelCalificacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCalificacionLayout.createSequentialGroup()
                .addGap(0, 12, Short.MAX_VALUE)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 608, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(panelCalificacionLayout.createSequentialGroup()
                .addGroup(panelCalificacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelCalificacionLayout.createSequentialGroup()
                        .addGap(217, 217, 217)
                        .addGroup(panelCalificacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnSalirdeQuiz, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(calificacion, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panelCalificacionLayout.createSequentialGroup()
                        .addGap(195, 195, 195)
                        .addComponent(TiempoTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelCalificacionLayout.setVerticalGroup(
            panelCalificacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCalificacionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(calificacion, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addComponent(TiempoTotal)
                .addGap(18, 18, 18)
                .addComponent(btnSalirdeQuiz, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(74, 74, 74))
        );

        panelContenedor.add(panelCalificacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 80, 630, 400));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/menu.png"))); // NOI18N
        panelContenedor.add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 890, 500));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelContenedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelContenedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void inicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inicioActionPerformed

        this.panelInicio.setVisible(true);
        this.panelHistorico.setVisible(false);
        this.panelConfig.setVisible(false);
        this.panelPlay.setVisible(false);
        this.panelCalificacion.setVisible(false);
        this.panelEducacion.setVisible(false);
        this.panelDatoCurioso.setVisible(false);
        this.panelEditConfig.setVisible(false);
        this.getPizarra1();

    }//GEN-LAST:event_inicioActionPerformed

    private void historicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_historicoActionPerformed
        // accion del boton historico
        this.consultaTablaHistorico();
        this.panelInicio.setVisible(false);
        this.panelHistorico.setVisible(true);
        this.panelConfig.setVisible(false);
        this.panelPlay.setVisible(false);
        this.panelCalificacion.setVisible(false);
        this.panelEducacion.setVisible(false);
        this.panelDatoCurioso.setVisible(false);
        this.panelEditConfig.setVisible(false);
    }//GEN-LAST:event_historicoActionPerformed

    private void jugarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jugarActionPerformed
        // accion del boton jugar
        this.panelInicio.setVisible(false);
        this.panelHistorico.setVisible(false);
        this.panelConfig.setVisible(false);
        this.panelPlay.setVisible(true);
        this.panelCalificacion.setVisible(false);
        this.panelEducacion.setVisible(false);
        this.panelDatoCurioso.setVisible(false);
        this.panelEditConfig.setVisible(false);
        this.recorridoPlay = 0;
        this.listaPreguntasPlay.clear();
        this.listaRespuestaPlay.clear();
        this.k = 0;
        this.totalPreguntasCorrectas = 0;
    }//GEN-LAST:event_jugarActionPerformed

    private void ConfiguracionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConfiguracionActionPerformed
        // accion del boton de configuracion de preguntas y respuestas
        this.panelInicio.setVisible(false);
        this.panelHistorico.setVisible(false);
        this.panelConfig.setVisible(true);
        this.panelPlay.setVisible(false);
        this.panelCalificacion.setVisible(false);
        this.panelEducacion.setVisible(false);
        this.panelDatoCurioso.setVisible(false);
        this.panelEditConfig.setVisible(false);
    }//GEN-LAST:event_ConfiguracionActionPerformed

    private void resp3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resp3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_resp3ActionPerformed

    private void cancelarPreguntaRespConfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarPreguntaRespConfActionPerformed
        // TODO add your handling code here:
        this.panelPlay.setVisible(false);
        this.panelQuiz.setVisible(false);
        this.panelConfig.setVisible(false);
        this.panelInicio.setVisible(true);
        preguntaConf.setText("");
        resp1.setText("");
        resp2.setText("");
        resp3.setText("");
        resp4.setText("");
        btnGrupoPreguntas.clearSelection();
    }//GEN-LAST:event_cancelarPreguntaRespConfActionPerformed

    private void btnSencilloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSencilloActionPerformed
        //Accion de seleccion de boton sencillo
        consultarPreguntasBD(5);

        this.panelPlay.setVisible(false);
        this.panelQuiz.setVisible(true);
        this.diseableMenuWhilePlaying();
        presentarPreguntaPlay(recorridoPlay);
        cronometro.start();
    }//GEN-LAST:event_btnSencilloActionPerformed

    private void btnNormalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNormalActionPerformed
        //Accion de seleccion de boton normal
        consultarPreguntasBD(10);

        this.panelPlay.setVisible(false);
        this.panelQuiz.setVisible(true);
        this.diseableMenuWhilePlaying();
        presentarPreguntaPlay(recorridoPlay);
        cronometro.start();
    }//GEN-LAST:event_btnNormalActionPerformed

    private void btnDificilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDificilActionPerformed
        //Accion de seleccion de boton dificil
        consultarPreguntasBD(20);

        this.panelPlay.setVisible(false);
        this.panelQuiz.setVisible(true);
        this.diseableMenuWhilePlaying();
        presentarPreguntaPlay(recorridoPlay);
        cronometro.start();
    }//GEN-LAST:event_btnDificilActionPerformed

    private void guardarPreguntaRespConfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarPreguntaRespConfActionPerformed
        // boton de accion para guardar configuracion de preguntas y respuestas
        if ( preguntaConf.getText().isEmpty() || resp1.getText().isEmpty() || resp2.getText().isEmpty() || resp3.getText().isEmpty() || resp4.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Por favor complete los datos correctamente para continuar");
            return;
        }
        tb_quiz tbQuiz = new tb_quiz();
        List<tb_respuestas> arrayRespuestas = new ArrayList<>();

        //obtener pregunta de la configuracion
        tbQuiz.setPregunta(preguntaConf.getText());

        String queryQuiz = "Insert into tb_Quiz (pregunta)"
                + "values(?) ";
        int idQuiz = 0; //reemplazar por el ID generado del insert
        try (Connection conn = conexionDB.getDbConnection(); PreparedStatement ps = conn.prepareStatement(queryQuiz, PreparedStatement.RETURN_GENERATED_KEYS)) {

            ps.setString(1, tbQuiz.getPregunta());
            ps.execute();
            try (ResultSet idGenerado = ps.getGeneratedKeys()) {
                if (idGenerado.next()) {
                    idQuiz = idGenerado.getInt(1);
                    System.out.println("id obtenido: " + idQuiz);
                }
            }

        } catch (Exception ex) {
            System.out.println("problemas con la insercion de la de pregunta: " + ex);
            return;
        }

        //Armamos neustro arreglo de respuesta
        arrayRespuestas.add(new tb_respuestas(resp1.getText(), validateBtn1.isSelected()));
        arrayRespuestas.add(new tb_respuestas(resp2.getText(), validateBtn2.isSelected()));
        arrayRespuestas.add(new tb_respuestas(resp3.getText(), validateBtn3.isSelected()));
        arrayRespuestas.add(new tb_respuestas(resp4.getText(), validateBtn4.isSelected()));
        //todo: falta agregar los demas valores de la respuesta

        String queryResponse = "insert into tb_quiz_Response (respuestas, validate, fk_id_quiz ) values(?,?,?)";

        try (Connection conn = conexionDB.getDbConnection(); PreparedStatement ps = conn.prepareStatement(queryResponse)) {
            int i = 0;
            for (tb_respuestas respuesta : arrayRespuestas) {
                ps.setString(1, respuesta.getRespuestas());
                ps.setBoolean(2, respuesta.isValidate());
                ps.setInt(3, idQuiz);

                ps.addBatch();
                i++;
                if (i % 1000 == 0 || i == arrayRespuestas.size()) {
                    ps.executeBatch(); // Execute every 1000 items.
                }
            }
            preguntaConf.setText("");
            resp1.setText("");
            resp2.setText("");
            resp3.setText("");
            resp4.setText("");
            btnGrupoPreguntas.clearSelection();
            JOptionPane.showMessageDialog(null, "Insercion de pregunta y respuesta exitosa!");
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Problemas con la insercion de la pregunta o respuesta: " + ex);
        }

    }//GEN-LAST:event_guardarPreguntaRespConfActionPerformed

    private void btnPlayNextQuestionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlayNextQuestionActionPerformed
        // TODO add your handling code here:
        
        almacenarOpcionEscogidaJuego();

        this.recorridoPlay += 1;

        this.labelNumPregunta.setText("Pregunta #" + (this.recorridoPlay + 1));

        this.rbPlayOpt1.setSelected(false);
        this.rbPlayOpt2.setSelected(false);
        this.rbPlayOpt3.setSelected(false);
        this.rbPlayOpt4.setSelected(false);

        this.playRespuesta1.setText("");
        this.playRespuesta2.setText("");
        this.playRespuesta3.setText("");
        this.playRespuesta4.setText("");

        System.out.println("Valor de recorrido: " + this.recorridoPlay
                + " Valor de total de lista: " + (this.listaPreguntasPlay.size() - 1));
        presentarPreguntaPlay(recorridoPlay);
        if (this.recorridoPlay >= this.listaPreguntasPlay.size() - 1) {
            this.btnFinalizarPlay.setEnabled(true);
            this.btnPlayNextQuestion.setEnabled(false);
        }
    }//GEN-LAST:event_btnPlayNextQuestionActionPerformed

    private void btnFinalizarPlayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFinalizarPlayActionPerformed
        // TODO add your handling code here:
       
        almacenarOpcionEscogidaJuego();

        int totalPreguntas = this.listaPreguntasPlay.size();

        for (RespuestaSeleccionUsuario seleccion : listaRespuestaPlay) {
            tb_quiz pregunta = this.listaPreguntasPlay.get(seleccion.getIndexPregunta());
            tb_respuestas respuesta = pregunta.getRespuestas().get(seleccion.getIndexRespuesta());
            if (respuesta.isValidate()) {
                this.totalPreguntasCorrectas++;
            }
        }

        this.panelCalificacion.setVisible(true);
        this.panelQuiz.setVisible(false);
        this.panelConfig.setVisible(false);
        this.panelPlay.setVisible(false);
        this.panelHistorico.setVisible(false);
        this.panelInicio.setVisible(false);

        calificacion.setText(this.totalPreguntasCorrectas + "/" + totalPreguntas);

        System.out.println("Total de preguntas " + totalPreguntas);
        System.out.println("Total de preguntas acertadas " + this.totalPreguntasCorrectas);

        // Detener el cronómetro
        etiquetaTiempo.setText(String.valueOf(k) + " segundos"); // Detener el cronómetro
        if (cronometro.isRunning()) {
            cronometro.stop();
        }

        int segundosTranscurridos = k;

        TiempoTotal.setText("Tiempo total: " + segundosTranscurridos + " segundos");
        TiempoTotal.setVisible(true); // Mostrar el JLabel tiempoTotal
    }//GEN-LAST:event_btnFinalizarPlayActionPerformed

    private void btnSalirdeQuizActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirdeQuizActionPerformed
        // clic al salir del juego
        int tiempoTranscurrido = k;

        LocalDate fechaActual = LocalDate.now();
        java.sql.Date fechaSql = java.sql.Date.valueOf(fechaActual);
        Object[] options = {"OK"};
        int result = JOptionPane.showOptionDialog(null, "Su calificación ha sido enviada al docente", "Evaluación finalizada", JOptionPane.DEFAULT_OPTION, JOptionPane.INFORMATION_MESSAGE, null, options, options[0]);
        if (result == JOptionPane.OK_OPTION) {
            this.panelCalificacion.setVisible(false);
            this.panelQuiz.setVisible(false);
            this.panelConfig.setVisible(false);
            this.panelPlay.setVisible(false);
            this.panelHistorico.setVisible(false);
            this.panelInicio.setVisible(true);

            this.diseableMenuWhilePlaying();

            String queryHistorico = "insert into tb_historico(fk_id_registros, nombreAlumno, ApellidoAlumno ,puntaje,fecha,tiempo_total) values (?,?,?,?,?,?) ";

            try (Connection conn = conexionDB.getDbConnection(); PreparedStatement ps = conn.prepareStatement(queryHistorico)) {

                ps.setInt(1, this.idLogin);
                ps.setString(2, this.nombreAlumno); //nombreAlumno
                ps.setString(3, this.apellidoAlumno); //apellidoAlumno
                ps.setInt(4, this.totalPreguntasCorrectas);
                ps.setDate(5, fechaSql);
                ps.setInt(6, tiempoTranscurrido);

                ps.execute();

            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null, "Error al insertar data en el histórico: " + ex);
            }
        }
    }//GEN-LAST:event_btnSalirdeQuizActionPerformed

    private void datoCuriosoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_datoCuriosoActionPerformed
        this.panelDatoCurioso.setVisible(true);
        this.panelInicio.setVisible(false);
        this.panelHistorico.setVisible(false);
        this.panelConfig.setVisible(false);
        this.panelPlay.setVisible(false);
        this.panelCalificacion.setVisible(false);
        this.panelEducacion.setVisible(false);
        this.getDatosCuriososPrimer();

    }//GEN-LAST:event_datoCuriosoActionPerformed

    private void actualizarTema1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actualizarTema1ActionPerformed
        String queryUpdateDato = "UPDATE tb_dato_curioso SET dato_curioso= ? WHERE idDato=1";

        tbDatoCurioso dato = new tbDatoCurioso();

        dato.setDato_curioso(temaEstudio1.getText());

        try (Connection conn = conexionDB.getDbConnection(); PreparedStatement ps = conn.prepareStatement(queryUpdateDato)) {
            ps.setString(1, dato.getDato_curioso());
            ps.executeUpdate();
            JOptionPane.showMessageDialog(null, "Actualizacion de tema exitoso");
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Error al actualizar el tema de estudio: " + ex);
        }
    }//GEN-LAST:event_actualizarTema1ActionPerformed

    private void actualizarTema2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actualizarTema2ActionPerformed
        String queryUpdateDato = "UPDATE tb_dato_curioso SET dato_curioso=? WHERE idDato=2";

        tbDatoCurioso dato = new tbDatoCurioso();
        dato.setDato_curioso(temaEstudio2.getText());

        try (Connection conn = conexionDB.getDbConnection(); PreparedStatement ps = conn.prepareStatement(queryUpdateDato)) {
            ps.setString(1, dato.getDato_curioso());
            ps.executeUpdate();
            JOptionPane.showMessageDialog(null, "Actualizacion de tema exitoso");
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Error al actualizar el tema de estudio: " + ex);
        }
    }//GEN-LAST:event_actualizarTema2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.panelInicio.setVisible(false);
        this.panelEducacion.setVisible(true);
        this.getPizarra2();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.panelInicio.setVisible(true);
        this.panelEducacion.setVisible(false);
        this.getPizarra1();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void rbPlayOpt3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbPlayOpt3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbPlayOpt3ActionPerformed

    private void rbPlayOpt2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbPlayOpt2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbPlayOpt2ActionPerformed

    private void rbPlayOpt4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbPlayOpt4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbPlayOpt4ActionPerformed

    private void preguntasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_preguntasActionPerformed
        this.panelInicio.setVisible(false);
        this.panelHistorico.setVisible(false);
        this.panelConfig.setVisible(false);
        this.panelPlay.setVisible(false);
        this.panelCalificacion.setVisible(false);
        this.panelEducacion.setVisible(false);
        this.panelDatoCurioso.setVisible(false);
        this.panelEditConfig.setVisible(true);
        this.consultarTablaPreguntas();
    }//GEN-LAST:event_preguntasActionPerformed

    private void tablaPreguntasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaPreguntasMouseClicked

        int column = tablaPreguntas.getColumnModel().getColumnIndexAtX(evt.getX());
        int row = evt.getY() / tablaPreguntas.getRowHeight();

        if (row < tablaPreguntas.getRowCount() && row >= 0 && column < tablaPreguntas.getColumnCount() && column >= 0) {
            Object value = tablaPreguntas.getValueAt(row, column);
            if (value instanceof JButton) {
                ((JButton) value).doClick();
                JButton boton = (JButton) value;
                Object idRegistro = tablaPreguntas.getValueAt(row, 0);

                int respuesta = JOptionPane.showConfirmDialog(
                        null,
                        "¿Desea Borrar el registro?",
                        "",
                        JOptionPane.YES_NO_OPTION,
                        JOptionPane.QUESTION_MESSAGE
                );

                if (respuesta == JOptionPane.YES_OPTION) {
                    String queryDelete = "DELETE tb_Quiz , tb_quiz_Response\n"
                            + "FROM tb_Quiz\n"
                            + "JOIN tb_quiz_Response ON tb_Quiz.idquiz = tb_quiz_Response.fk_id_quiz\n"
                            + "WHERE idquiz = ?;";

                    try (Connection conn = conexionDB.getDbConnection(); PreparedStatement ps = conn.prepareStatement(queryDelete)) {
                        ps.setString(1, idRegistro.toString());
                        ps.execute();
                        this.consultarTablaPreguntas();
                        JOptionPane.showMessageDialog(null, "Registro eliminado con éxito!");
                    } catch (Exception ex) {
                        JOptionPane.showMessageDialog(null, "Hubo problemas con la eliminación: " + ex);
                    }

                }

            }
        }

    }//GEN-LAST:event_tablaPreguntasMouseClicked

    public void getDatosCuriososPrimer() {

        String queryConsultaDatoCurioso = "select * from tb_dato_curioso where idDato= 1";
        String queryConsultaDatoCurioso2 = "select * from tb_dato_curioso where idDato= 2";

        try (Connection conn = conexionDB.getDbConnection(); PreparedStatement ps = conn.prepareStatement(queryConsultaDatoCurioso)) {
            try (ResultSet rs = ps.executeQuery()) {
                if (rs.next()) {
                    String temaEstudio = rs.getString("dato_curioso");
                    temaEstudio1.setText(temaEstudio);
                }
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Error al presentar la data anterior: " + ex);
        }

        try (Connection conn = conexionDB.getDbConnection(); PreparedStatement ps = conn.prepareStatement(queryConsultaDatoCurioso2)) {
            try (ResultSet rs = ps.executeQuery()) {
                if (rs.next()) {
                    String temaEstudio = rs.getString("dato_curioso");
                    temaEstudio2.setText(temaEstudio);
                }
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Error al presentar la data anterior: " + ex);
        }

    }

    public void getPizarra1() {
        String queryConsultaDatoCurioso = "select * from tb_dato_curioso where idDato= 1";

        try (Connection conn = conexionDB.getDbConnection(); PreparedStatement ps = conn.prepareStatement(queryConsultaDatoCurioso)) {
            try (ResultSet rs = ps.executeQuery()) {
                if (rs.next()) {
                    String temaEstudio = rs.getString("dato_curioso");
                    pizarra1.setText(temaEstudio);
                }
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Error al presentar la data anterior: " + ex);
        }

    }

    public void getPizarra2() {

        String queryConsultaDatoCurioso2 = "select * from tb_dato_curioso where idDato= 2";
        try (Connection conn = conexionDB.getDbConnection(); PreparedStatement ps = conn.prepareStatement(queryConsultaDatoCurioso2)) {
            try (ResultSet rs = ps.executeQuery()) {
                if (rs.next()) {
                    String temaEstudio = rs.getString("dato_curioso");
                    pizarra2.setText(temaEstudio);
                }
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Error al presentar la data anterior: " + ex);
        }
    }

    public void almacenarOpcionEscogidaJuego() {
        int opcionSeleccionada = -1;
        if (rbPlayOpt1.isSelected()) {
            opcionSeleccionada = 0;
        } else if (rbPlayOpt2.isSelected()) {
            opcionSeleccionada = 1;
        } else if (rbPlayOpt3.isSelected()) {
            opcionSeleccionada = 2;
        } else if (rbPlayOpt4.isSelected()) {
            opcionSeleccionada = 3;
        }

        listaRespuestaPlay.add(new RespuestaSeleccionUsuario(
                this.recorridoPlay,
                opcionSeleccionada
        ));
    }

    public void inhabilitaOpcionesUsuario(int idPersona) {
        if (idPersona == 2) { //alumno
            Configuracion.setVisible(false);
            historico.setVisible(false);
            datoCurioso.setVisible(false);
        } else { //docente
            Configuracion.setVisible(true);
            historico.setVisible(true);
            datoCurioso.setVisible(true);
        }
    }

    public void obtenerNombreAlumnoLogin(String nombre) {
        this.nombreAlumno = nombre;
    }

    public void obtenerApellidoAlumnoLogin(String apellido) {
        this.apellidoAlumno = apellido;
    }

    public void obtenerIdLogin(int idLogin) {
        this.idLogin = idLogin;
    }

    void presentarPreguntaPlay(int recorrido) {
        tb_quiz quiz = listaPreguntasPlay.get(recorrido);
        this.playPregunta.setText(quiz.getPregunta());
        List<tb_respuestas> listResp = quiz.getRespuestas() == null
                ? Collections.emptyList() : quiz.getRespuestas();
        for (int i = 0; i < listResp.size(); i++) {
            if (i == 0) {
                this.playRespuesta1.setText(listResp.get(0).getRespuestas());
            }

            if (i == 1) {
                this.playRespuesta2.setText(listResp.get(1).getRespuestas());
            }

            if (i == 2) {
                this.playRespuesta3.setText(listResp.get(2).getRespuestas());
            }

            if (i == 3) {
                this.playRespuesta4.setText(listResp.get(3).getRespuestas());
            }
        }
    }

    public void diseableMenuWhilePlaying() {

        if (this.panelQuiz.isVisible()) {
            this.inicio.setEnabled(false);
            this.Configuracion.setEnabled(false);
            this.jugar.setEnabled(false);
            this.historico.setEnabled(false);
            this.datoCurioso.setEnabled(false);
            this.preguntas.setEnabled(false);
        } else {
            this.inicio.setEnabled(true);
            this.Configuracion.setEnabled(true);
            this.jugar.setEnabled(true);
            this.historico.setEnabled(true);
            this.datoCurioso.setEnabled(true);
            this.preguntas.setEnabled(true);
        }
    }

    public void restartPlay() {
        this.recorridoPlay = 0;
        listaPreguntasPlay.clear();
        listaRespuestaPlay.clear();

        this.btnFinalizarPlay.setEnabled(false);
        this.btnPlayNextQuestion.setEnabled(true);
        this.labelNumPregunta.setText("Pregunta #1");
    }

    public void consultarPreguntasBD(int maxPreguntas) {
        restartPlay();

        String queryPreguntas = "select * from tb_Quiz order by rand() limit ?";

        try (Connection conn = conexionDB.getDbConnection(); PreparedStatement ps = conn.prepareStatement(queryPreguntas)) {
            ps.setInt(1, maxPreguntas);

            try (ResultSet rs = ps.executeQuery()) {
                while (rs.next()) {
                    tb_quiz quiz = new tb_quiz(rs.getInt("idquiz"),
                            rs.getString("pregunta"),
                            consultaRespuestasByIdQuiz(conn, rs.getInt("idquiz")));

                    listaPreguntasPlay.add(quiz);
                }
            }
        } catch (Exception ex) {
            System.err.println("Error en cargar preguntas: " + ex.getMessage());
        }
        System.out.println("Lista preguntas " + listaPreguntasPlay.toString());
    }

    private List<tb_respuestas> consultaRespuestasByIdQuiz(Connection conn, int idQuiz) {
        List<tb_respuestas> listaRespuestas = new ArrayList<>();
        String queryRespuestas = "select * from tb_quiz_Response where fk_id_quiz = ?";
        try (PreparedStatement ps = conn.prepareCall(queryRespuestas)) {
            ps.setInt(1, idQuiz);

            try (ResultSet rs = ps.executeQuery()) {
                while (rs.next()) {
                    tb_respuestas response = new tb_respuestas(
                            rs.getInt("idQuizResponse"),
                            rs.getString("respuestas"),
                            rs.getInt("validate") == 1
                    );
                    listaRespuestas.add(response);
                }
            }
        } catch (Exception ex) {
            System.err.println("Error en cargar respuestas: " + ex.getMessage());
            listaRespuestas = Collections.emptyList();
        }
        return listaRespuestas;
    }

    public void consultaTablaHistorico() {
        DefaultTableModel dataTable = new DefaultTableModel();
        dataTable.addColumn("Nombre");
        dataTable.addColumn("Apellido");
        dataTable.addColumn("Calificación");
        dataTable.addColumn("Fecha");
        dataTable.addColumn("Tiempo(s)");
        //dataTable.addColumn("");

        String queryHistorico = "Select * from tb_historico";

        try (Connection conn = conexionDB.getDbConnection(); PreparedStatement ps = conn.prepareStatement(queryHistorico)) {
            try (ResultSet rs = ps.executeQuery()) {
                while (rs.next()) {
                    dataTable.addRow(new Object[]{rs.getString("nombreAlumno"), rs.getString("apellidoAlumno"), rs.getInt("puntaje"), rs.getDate("fecha"), rs.getInt("tiempo_total")});
                }
            }
        } catch (Exception e) {
        }

        this.tablaHistorico.setModel(dataTable);

    }

    public void consultarTablaPreguntas() {
        DefaultTableModel dataTable = new DefaultTableModel();
        dataTable.addColumn("No.");
        dataTable.addColumn("Pregunta");
        dataTable.addColumn("Acción");

        String querypreguntas = "Select * from tb_Quiz";
        tablaPreguntas.setDefaultRenderer(Object.class, new render());
        JButton deleteBtn = new JButton("Eliminar");

        try (Connection conn = conexionDB.getDbConnection(); PreparedStatement ps = conn.prepareStatement(querypreguntas)) {
            try (ResultSet rs = ps.executeQuery()) {
                while (rs.next()) {
                    dataTable.addRow(new Object[]{rs.getString("idQuiz"), rs.getString("pregunta"), deleteBtn});
                }
            }
        } catch (Exception e) {
        }
        this.tablaPreguntas.setRowHeight(30);
        this.tablaPreguntas.setModel(dataTable);

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Configuracion;
    private javax.swing.JLabel TiempoTotal;
    private javax.swing.JButton actualizarTema1;
    private javax.swing.JButton actualizarTema2;
    private javax.swing.JLabel background;
    private javax.swing.JButton btnDificil;
    private javax.swing.JButton btnFinalizarPlay;
    private javax.swing.ButtonGroup btnGrupoConfigPreguntas;
    private javax.swing.ButtonGroup btnGrupoPreguntas;
    private javax.swing.JButton btnNormal;
    private javax.swing.JButton btnPlayNextQuestion;
    private javax.swing.JButton btnSalirdeQuiz;
    private javax.swing.JButton btnSencillo;
    private javax.swing.JLabel calificacion;
    private javax.swing.JButton cancelarPreguntaRespConf;
    private javax.swing.JButton datoCurioso;
    private javax.swing.JLabel etiquetaTiempo;
    private javax.swing.JButton guardarPreguntaRespConf;
    private javax.swing.JButton historico;
    private javax.swing.JButton inicio;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JButton jugar;
    private javax.swing.JLabel labelNumPregunta;
    private javax.swing.JPanel panelCalificacion;
    private javax.swing.JPanel panelConfig;
    private javax.swing.JPanel panelContenedor;
    private javax.swing.JPanel panelDatoCurioso;
    private javax.swing.JPanel panelEditConfig;
    private javax.swing.JPanel panelEducacion;
    private javax.swing.JPanel panelHistorico;
    private javax.swing.JPanel panelInicio;
    private javax.swing.JPanel panelPlay;
    private javax.swing.JPanel panelQuiz;
    private javax.swing.JTextArea pizarra1;
    private javax.swing.JTextArea pizarra2;
    private javax.swing.JTextArea playPregunta;
    private javax.swing.JTextArea playRespuesta1;
    private javax.swing.JTextArea playRespuesta2;
    private javax.swing.JTextArea playRespuesta3;
    private javax.swing.JTextArea playRespuesta4;
    private javax.swing.JTextField preguntaConf;
    private javax.swing.JButton preguntas;
    private javax.swing.JRadioButton rbPlayOpt1;
    private javax.swing.JRadioButton rbPlayOpt2;
    private javax.swing.JRadioButton rbPlayOpt3;
    private javax.swing.JRadioButton rbPlayOpt4;
    private javax.swing.JTextField resp1;
    private javax.swing.JTextField resp2;
    private javax.swing.JTextField resp3;
    private javax.swing.JTextField resp4;
    private javax.swing.JTable tablaHistorico;
    private javax.swing.JTable tablaPreguntas;
    private javax.swing.JTextArea temaEstudio1;
    private javax.swing.JTextArea temaEstudio2;
    private javax.swing.JRadioButton validateBtn1;
    private javax.swing.JRadioButton validateBtn2;
    private javax.swing.JRadioButton validateBtn3;
    private javax.swing.JRadioButton validateBtn4;
    // End of variables declaration//GEN-END:variables
}
